// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ApiResponseData,
} from './';

/**
 * @export
 * @interface ApiResponse
 */
export interface ApiResponse {
    /**
     * @type {boolean}
     * @memberof ApiResponse
     */
    success?: boolean;
    /**
     * @type {ApiResponseData}
     * @memberof ApiResponse
     */
    data?: ApiResponseData;
    /**
     * @type {string}
     * @memberof ApiResponse
     */
    message?: string;
    /**
     * 数据总数（用于列表接口）
     * @type {number}
     * @memberof ApiResponse
     */
    count?: number;
}
