// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ApiStatsPriorityGet200ResponseDataHigh
 */
export interface ApiStatsPriorityGet200ResponseDataHigh {
    /**
     * @type {number}
     * @memberof ApiStatsPriorityGet200ResponseDataHigh
     */
    total?: number;
    /**
     * @type {number}
     * @memberof ApiStatsPriorityGet200ResponseDataHigh
     */
    pending?: number;
    /**
     * @type {number}
     * @memberof ApiStatsPriorityGet200ResponseDataHigh
     */
    inProgress?: number;
    /**
     * @type {number}
     * @memberof ApiStatsPriorityGet200ResponseDataHigh
     */
    completed?: number;
}
