// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ApiStatsPriorityGet200ResponseDataHigh,
} from './';

/**
 * @export
 * @interface ApiStatsPriorityGet200ResponseData
 */
export interface ApiStatsPriorityGet200ResponseData {
    /**
     * @type {ApiStatsPriorityGet200ResponseDataHigh}
     * @memberof ApiStatsPriorityGet200ResponseData
     */
    high?: ApiStatsPriorityGet200ResponseDataHigh;
    /**
     * @type {ApiStatsPriorityGet200ResponseDataHigh}
     * @memberof ApiStatsPriorityGet200ResponseData
     */
    medium?: ApiStatsPriorityGet200ResponseDataHigh;
    /**
     * @type {ApiStatsPriorityGet200ResponseDataHigh}
     * @memberof ApiStatsPriorityGet200ResponseData
     */
    low?: ApiStatsPriorityGet200ResponseDataHigh;
}
