// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ApiStatsCompletionRateGet200ResponseData,
} from './';

/**
 * @export
 * @interface ApiStatsCompletionRateGet200Response
 */
export interface ApiStatsCompletionRateGet200Response {
    /**
     * @type {boolean}
     * @memberof ApiStatsCompletionRateGet200Response
     */
    success?: boolean;
    /**
     * @type {ApiStatsCompletionRateGet200ResponseData}
     * @memberof ApiStatsCompletionRateGet200Response
     */
    data?: ApiStatsCompletionRateGet200ResponseData;
}
