// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Todo,
} from './';

/**
 * @export
 * @interface ApiTodosGet200Response
 */
export interface ApiTodosGet200Response {
    /**
     * @type {boolean}
     * @memberof ApiTodosGet200Response
     */
    success?: boolean;
    /**
     * @type {Array<Todo>}
     * @memberof ApiTodosGet200Response
     */
    data?: Array<Todo>;
    /**
     * @type {number}
     * @memberof ApiTodosGet200Response
     */
    total?: number;
    /**
     * @type {number}
     * @memberof ApiTodosGet200Response
     */
    page?: number;
    /**
     * @type {number}
     * @memberof ApiTodosGet200Response
     */
    size?: number;
}
