// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Get200ResponseEndpoints,
} from './';

/**
 * @export
 * @interface Get200Response
 */
export interface Get200Response {
    /**
     * @type {string}
     * @memberof Get200Response
     */
    message?: string;
    /**
     * @type {string}
     * @memberof Get200Response
     */
    version?: string;
    /**
     * @type {Get200ResponseEndpoints}
     * @memberof Get200Response
     */
    endpoints?: Get200ResponseEndpoints;
}
