// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UserInput
 */
export interface UserInput {
    /**
     * 用户姓名
     * @type {string}
     * @memberof UserInput
     */
    name: string;
    /**
     * 用户邮箱
     * @type {string}
     * @memberof UserInput
     */
    email: string;
    /**
     * 用户年龄
     * @type {number}
     * @memberof UserInput
     */
    age?: number;
    /**
     * 用户头像URL
     * @type {string}
     * @memberof UserInput
     */
    avatar?: string;
}
