// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    User,
} from './';

/**
 * @export
 * @interface ApiAuthProfilePut200Response
 */
export interface ApiAuthProfilePut200Response {
    /**
     * @type {boolean}
     * @memberof ApiAuthProfilePut200Response
     */
    success?: boolean;
    /**
     * @type {User}
     * @memberof ApiAuthProfilePut200Response
     */
    data?: User;
    /**
     * @type {string}
     * @memberof ApiAuthProfilePut200Response
     */
    message?: string;
}
