// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ApiLogsGet200ResponseDataInner
 */
export interface ApiLogsGet200ResponseDataInner {
    /**
     * @type {string}
     * @memberof ApiLogsGet200ResponseDataInner
     */
    name?: string;
    /**
     * @type {number}
     * @memberof ApiLogsGet200ResponseDataInner
     */
    size?: number;
    /**
     * @type {string}
     * @memberof ApiLogsGet200ResponseDataInner
     */
    modified?: string;
    /**
     * @type {string}
     * @memberof ApiLogsGet200ResponseDataInner
     */
    type?: ApiLogsGet200ResponseDataInnerTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ApiLogsGet200ResponseDataInnerTypeEnum {
    error = 'error',
    combined = 'combined',
    http = 'http',
    exceptions = 'exceptions',
    rejections = 'rejections'
}

