// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ApiLogsFilenameGet200ResponseData
 */
export interface ApiLogsFilenameGet200ResponseData {
    /**
     * @type {string}
     * @memberof ApiLogsFilenameGet200ResponseData
     */
    filename?: string;
    /**
     * @type {string}
     * @memberof ApiLogsFilenameGet200ResponseData
     */
    content?: string;
    /**
     * @type {number}
     * @memberof ApiLogsFilenameGet200ResponseData
     */
    totalLines?: number;
    /**
     * @type {number}
     * @memberof ApiLogsFilenameGet200ResponseData
     */
    returnedLines?: number;
}
