// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ApiStatsTimelineGet200ResponseDataInner,
} from './';

/**
 * @export
 * @interface ApiStatsTimelineGet200Response
 */
export interface ApiStatsTimelineGet200Response {
    /**
     * @type {boolean}
     * @memberof ApiStatsTimelineGet200Response
     */
    success?: boolean;
    /**
     * @type {Array<ApiStatsTimelineGet200ResponseDataInner>}
     * @memberof ApiStatsTimelineGet200Response
     */
    data?: Array<ApiStatsTimelineGet200ResponseDataInner>;
}
