// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ApiStatsCompletionRateGet200ResponseData
 */
export interface ApiStatsCompletionRateGet200ResponseData {
    /**
     * 总体完成率
     * @type {number}
     * @memberof ApiStatsCompletionRateGet200ResponseData
     */
    overall?: number;
    /**
     * 本周完成率
     * @type {number}
     * @memberof ApiStatsCompletionRateGet200ResponseData
     */
    thisWeek?: number;
    /**
     * 本月完成率
     * @type {number}
     * @memberof ApiStatsCompletionRateGet200ResponseData
     */
    thisMonth?: number;
    /**
     * 平均完成时间（小时）
     * @type {number}
     * @memberof ApiStatsCompletionRateGet200ResponseData
     */
    averageCompletionTime?: number;
}
