// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Todo,
} from './';

/**
 * @export
 * @interface ApiTodosPost201Response
 */
export interface ApiTodosPost201Response {
    /**
     * @type {boolean}
     * @memberof ApiTodosPost201Response
     */
    success?: boolean;
    /**
     * @type {Todo}
     * @memberof ApiTodosPost201Response
     */
    data?: Todo;
}
