// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    User,
} from './';

/**
 * @export
 * @interface AuthResponseData
 */
export interface AuthResponseData {
    /**
     * @type {User}
     * @memberof AuthResponseData
     */
    user?: User;
    /**
     * 访问令牌
     * @type {string}
     * @memberof AuthResponseData
     */
    token?: string;
    /**
     * 刷新令牌
     * @type {string}
     * @memberof AuthResponseData
     */
    refreshToken?: string;
    /**
     * token过期时间（秒）
     * @type {number}
     * @memberof AuthResponseData
     */
    expiresIn?: number;
    /**
     * refresh token过期时间（秒）
     * @type {number}
     * @memberof AuthResponseData
     */
    refreshExpiresIn?: number;
}
