// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    UpdateTodoData,
} from './';

/**
 * @export
 * @interface BatchOperation
 */
export interface BatchOperation {
    /**
     * 操作类型
     * @type {string}
     * @memberof BatchOperation
     */
    action: BatchOperationActionEnum;
    /**
     * 任务ID列表
     * @type {Array<string>}
     * @memberof BatchOperation
     */
    ids: Array<string>;
    /**
     * 更新数据（仅在action为update时需要）
     * @type {UpdateTodoData}
     * @memberof BatchOperation
     */
    data?: UpdateTodoData;
}

/**
 * @export
 * @enum {string}
 */
export enum BatchOperationActionEnum {
    delete = 'delete',
    update = 'update'
}

