// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CreateTodoData
 */
export interface CreateTodoData {
    /**
     * 任务标题
     * @type {string}
     * @memberof CreateTodoData
     */
    title: string;
    /**
     * 任务描述
     * @type {string}
     * @memberof CreateTodoData
     */
    description?: string;
    /**
     * 任务优先级
     * @type {string}
     * @memberof CreateTodoData
     */
    priority?: CreateTodoDataPriorityEnum;
    /**
     * 任务标签
     * @type {Array<string>}
     * @memberof CreateTodoData
     */
    tags?: Array<string>;
    /**
     * 截止日期
     * @type {string}
     * @memberof CreateTodoData
     */
    dueDate?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateTodoDataPriorityEnum {
    high = 'high',
    medium = 'medium',
    low = 'low'
}

