// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface DeleteAccountRequest
 */
export interface DeleteAccountRequest {
    /**
     * 用户密码（用于验证身份）
     * @type {string}
     * @memberof DeleteAccountRequest
     */
    password: string;
    /**
     * 确认文本（可选），必须为 \"DELETE MY ACCOUNT\"
     * @type {string}
     * @memberof DeleteAccountRequest
     */
    confirmText?: string;
}
