// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface LogoutRequest
 */
export interface LogoutRequest {
    /**
     * 访问令牌（可选）
     * @type {string}
     * @memberof LogoutRequest
     */
    token?: string;
    /**
     * 刷新令牌（可选）
     * @type {string}
     * @memberof LogoutRequest
     */
    refreshToken?: string;
}
