// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    RefreshTokenResponseData,
} from './';

/**
 * @export
 * @interface RefreshTokenResponse
 */
export interface RefreshTokenResponse {
    /**
     * @type {boolean}
     * @memberof RefreshTokenResponse
     */
    success?: boolean;
    /**
     * @type {RefreshTokenResponseData}
     * @memberof RefreshTokenResponse
     */
    data?: RefreshTokenResponseData;
    /**
     * @type {string}
     * @memberof RefreshTokenResponse
     */
    message?: string;
}
