// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RefreshTokenResponseData
 */
export interface RefreshTokenResponseData {
    /**
     * 新的访问令牌
     * @type {string}
     * @memberof RefreshTokenResponseData
     */
    token?: string;
    /**
     * 新的刷新令牌
     * @type {string}
     * @memberof RefreshTokenResponseData
     */
    refreshToken?: string;
}
