// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RegisterRequest
 */
export interface RegisterRequest {
    /**
     * 用户姓名（可选，默认使用邮箱前缀）
     * @type {string}
     * @memberof RegisterRequest
     */
    name?: string;
    /**
     * 用户邮箱（必须唯一）
     * @type {string}
     * @memberof RegisterRequest
     */
    email: string;
    /**
     * 用户密码
     * @type {string}
     * @memberof RegisterRequest
     */
    password: string;
    /**
     * 确认密码
     * @type {string}
     * @memberof RegisterRequest
     */
    confirm_password: string;
}
