// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Todo
 */
export interface Todo {
    /**
     * 任务ID
     * @type {string}
     * @memberof Todo
     */
    id?: string;
    /**
     * 任务标题
     * @type {string}
     * @memberof Todo
     */
    title?: string;
    /**
     * 任务描述
     * @type {string}
     * @memberof Todo
     */
    description?: string;
    /**
     * 任务状态
     * @type {string}
     * @memberof Todo
     */
    status?: TodoStatusEnum;
    /**
     * 任务优先级
     * @type {string}
     * @memberof Todo
     */
    priority?: TodoPriorityEnum;
    /**
     * 任务标签
     * @type {Array<string>}
     * @memberof Todo
     */
    tags?: Array<string>;
    /**
     * 截止日期
     * @type {string}
     * @memberof Todo
     */
    dueDate?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof Todo
     */
    createdAt?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof Todo
     */
    updatedAt?: string;
    /**
     * 完成时间
     * @type {string}
     * @memberof Todo
     */
    completedAt?: string;
    /**
     * 排序顺序
     * @type {number}
     * @memberof Todo
     */
    order?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum TodoStatusEnum {
    pending = 'pending',
    in_progress = 'in-progress',
    completed = 'completed'
}
/**
 * @export
 * @enum {string}
 */
export enum TodoPriorityEnum {
    high = 'high',
    medium = 'medium',
    low = 'low'
}

