// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    TodoStatsTagStatsInner,
} from './';

/**
 * @export
 * @interface TodoStats
 */
export interface TodoStats {
    /**
     * 总任务数
     * @type {number}
     * @memberof TodoStats
     */
    total?: number;
    /**
     * 待办任务数
     * @type {number}
     * @memberof TodoStats
     */
    pending?: number;
    /**
     * 进行中任务数
     * @type {number}
     * @memberof TodoStats
     */
    inProgress?: number;
    /**
     * 已完成任务数
     * @type {number}
     * @memberof TodoStats
     */
    completed?: number;
    /**
     * 过期任务数
     * @type {number}
     * @memberof TodoStats
     */
    overdue?: number;
    /**
     * 标签统计
     * @type {Array<TodoStatsTagStatsInner>}
     * @memberof TodoStats
     */
    tagStats?: Array<TodoStatsTagStatsInner>;
}
