// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type {
    Get200Response,
    HealthResponse,
} from '../models';

/**
 * no description
 */
export class HealthApi extends BaseAPI {

    /**
     * 检查服务器运行状态
     * 健康检查
     */
    healthGet(): Observable<HealthResponse>
    healthGet(opts?: OperationOpts): Observable<AjaxResponse<HealthResponse>>
    healthGet(opts?: OperationOpts): Observable<HealthResponse | AjaxResponse<HealthResponse>> {
        return this.request<HealthResponse>({
            url: '/health',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * 获取API基本信息和可用端点
     * API欢迎页面
     */
    rootGet(): Observable<Get200Response>
    rootGet(opts?: OperationOpts): Observable<AjaxResponse<Get200Response>>
    rootGet(opts?: OperationOpts): Observable<Get200Response | AjaxResponse<Get200Response>> {
        return this.request<Get200Response>({
            url: '/',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
