// tslint:disable
/**
 * Express.js Backend API
 * 一个专为前端工程师设计的Express.js后端API模板
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpQuery } from '../runtime';
import type {
    ApiStatsCompletionRateGet200Response,
    ApiStatsGet200Response,
    ApiStatsPriorityGet200Response,
    ApiStatsTimelineGet200Response,
} from '../models';

export interface ApiStatsTimelineGetRequest {
    days?: number;
}

/**
 * no description
 */
export class StatsApi extends BaseAPI {

    /**
     * 获取任务完成率相关统计
     * 获取完成率统计
     */
    apiStatsCompletionRateGet(): Observable<ApiStatsCompletionRateGet200Response>
    apiStatsCompletionRateGet(opts?: OperationOpts): Observable<AjaxResponse<ApiStatsCompletionRateGet200Response>>
    apiStatsCompletionRateGet(opts?: OperationOpts): Observable<ApiStatsCompletionRateGet200Response | AjaxResponse<ApiStatsCompletionRateGet200Response>> {
        return this.request<ApiStatsCompletionRateGet200Response>({
            url: '/api/stats/completion-rate',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * 获取任务的各种统计数据，包括总数、状态分布、过期任务等
     * 获取任务统计信息
     */
    apiStatsGet(): Observable<ApiStatsGet200Response>
    apiStatsGet(opts?: OperationOpts): Observable<AjaxResponse<ApiStatsGet200Response>>
    apiStatsGet(opts?: OperationOpts): Observable<ApiStatsGet200Response | AjaxResponse<ApiStatsGet200Response>> {
        return this.request<ApiStatsGet200Response>({
            url: '/api/stats',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * 获取按优先级分组的任务统计
     * 获取优先级统计
     */
    apiStatsPriorityGet(): Observable<ApiStatsPriorityGet200Response>
    apiStatsPriorityGet(opts?: OperationOpts): Observable<AjaxResponse<ApiStatsPriorityGet200Response>>
    apiStatsPriorityGet(opts?: OperationOpts): Observable<ApiStatsPriorityGet200Response | AjaxResponse<ApiStatsPriorityGet200Response>> {
        return this.request<ApiStatsPriorityGet200Response>({
            url: '/api/stats/priority',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * 获取按日期分组的任务完成统计
     * 获取时间线统计
     */
    apiStatsTimelineGet({ days }: ApiStatsTimelineGetRequest): Observable<ApiStatsTimelineGet200Response>
    apiStatsTimelineGet({ days }: ApiStatsTimelineGetRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiStatsTimelineGet200Response>>
    apiStatsTimelineGet({ days }: ApiStatsTimelineGetRequest, opts?: OperationOpts): Observable<ApiStatsTimelineGet200Response | AjaxResponse<ApiStatsTimelineGet200Response>> {

        const query: HttpQuery = {};

        if (days != null) { query['days'] = days; }

        return this.request<ApiStatsTimelineGet200Response>({
            url: '/api/stats/timeline',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

}
